import { Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/ui/header";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "SensAI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <ClerkProvider>
    
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
             <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p> &copy;2025 MohitBhargav</p>

              </div>
            </footer>
       </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
